//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.InterfaceWeb.Commanding {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Commanding.ISimpleTwitterCommandService")]
    public interface ISimpleTwitterCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/Execute", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/ExecuteResponse")]
        void Execute(Gerenciador.Comandos.PostNewTweetCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleTwitterCommandServiceChannel : Gerenciador.InterfaceWeb.Commanding.ISimpleTwitterCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleTwitterCommandServiceClient : System.ServiceModel.ClientBase<Gerenciador.InterfaceWeb.Commanding.ISimpleTwitterCommandService>, Gerenciador.InterfaceWeb.Commanding.ISimpleTwitterCommandService {
        
        public SimpleTwitterCommandServiceClient() {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Execute(Gerenciador.Comandos.PostNewTweetCommand command) {
            base.Channel.Execute(command);
        }
    }
}
